packages: []
catalogs:
  build:
    tsdown: ^0.14.2
  cli:
    bumpp: ^10.2.3
    pncat: ^0.5.0
    taze: ^19.3.0
  dev:
    typescript: ^5.9.2
  lint:
    '@antfu/eslint-config': ^5.2.1
    eslint: ^9.34.0
    lint-staged: ^16.1.5
    simple-git-hooks: ^2.13.1
  test:
    '@vitest/coverage-v8': 3.2.4
    vitest: ^3.2.4
  types:
    '@types/node': ^24.3.0
