packages: []
catalogs:
  build:
    tsdown: ^0.12.9
  cli:
    bumpp: ^10.2.0
    czg: ^1.11.2
    pncat: ^0.2.6
    taze: ^19.1.0
  dev:
    '@octohash/tsconfig': ^0.1.0
    typescript: ^5.8.3
  lint:
    '@antfu/eslint-config': ^4.16.2
    eslint: ^9.30.1
    lint-staged: ^16.1.2
    simple-git-hooks: ^2.13.0
  test:
    '@vitest/coverage-v8': 3.2.4
    vitest: ^3.2.4
  types:
    '@types/node': ^24.0.10
