packages: []
catalogs:
  build:
    tsdown: ^0.13.3
  cli:
    bumpp: ^10.2.2
    czg: ^1.12.0
    pncat: ^0.4.1
    taze: ^19.1.0
  dev:
    '@octohash/tsconfig': ^0.1.0
    typescript: ^5.9.2
  lint:
    '@antfu/eslint-config': ^5.2.0
    eslint: ^9.32.0
    lint-staged: ^16.1.4
    simple-git-hooks: ^2.13.1
  test:
    '@vitest/coverage-v8': 3.2.4
    vitest: ^3.2.4
  types:
    '@types/node': ^24.2.0
